@extends('layouts.public', ['title' => 'حسابي'])

@section('content')
<section class="mx-auto w-full max-w-6xl space-y-8 px-4 py-8 sm:px-6 sm:py-12 lg:px-8" dir="rtl">
    <header class="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end">
        <div><p class="text-sm font-medium text-emerald-700 dark:text-emerald-300">رمز العضوية · <bdi>{{ $profile->member_code }}</bdi></p><h1 class="mt-2 font-heading text-3xl font-semibold text-emerald-950 dark:text-white sm:text-4xl">مرحبًا، {{ $profile->familyMember->name }}</h1><p class="mt-3 max-w-xl text-sm leading-7 text-emerald-900/65 dark:text-white/65">كل ما يخص طلباتك ومحفظتك في مكان واحد.</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('coffee') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-sm bg-emerald-800 px-5 text-sm font-semibold text-white transition hover:bg-emerald-900 active:translate-y-px dark:bg-emerald-300 dark:text-emerald-950"><x-hugeicon name="sparkles" class="text-lg" />تصفح القهوة</a><form method="POST" action="{{ route('minor.logout') }}">@csrf<button type="submit" class="inline-flex min-h-11 items-center justify-center rounded-sm border border-emerald-900/15 px-4 text-sm font-semibold text-emerald-900 transition hover:bg-white active:translate-y-px dark:border-white/15 dark:text-white dark:hover:bg-white/10">تسجيل الخروج</button></form></div>
    </header>

    <x-minor-panel-nav />

    <section class="grid gap-px overflow-hidden rounded-2xl bg-emerald-900/10 ring-1 ring-emerald-900/10 dark:bg-white/10 dark:ring-white/10 sm:grid-cols-3" aria-label="ملخص الحساب">
        <a href="#wallet" class="bg-white p-5 transition hover:bg-emerald-50 dark:bg-zinc-900 dark:hover:bg-zinc-800"><p class="text-xs font-medium text-emerald-900/55 dark:text-white/55">الرصيد المتاح</p><p class="mt-2 text-2xl font-semibold text-emerald-950 dark:text-white">@if ($wallet)<x-money :amount-baisa="max(0, $wallet->balance_baisa - $reservedBalance)" :currency="$wallet->currency" />@else — @endif</p></a>
        <a href="{{ route('minor.orders.index') }}" class="bg-white p-5 transition hover:bg-emerald-50 dark:bg-zinc-900 dark:hover:bg-zinc-800"><p class="text-xs font-medium text-emerald-900/55 dark:text-white/55">طلبات قيد المتابعة</p><p class="mt-2 text-2xl font-semibold text-emerald-950 dark:text-white">{{ $activeOrdersCount }}</p></a>
        <a href="{{ route('minor.notifications.index') }}" class="bg-white p-5 transition hover:bg-emerald-50 dark:bg-zinc-900 dark:hover:bg-zinc-800"><p class="text-xs font-medium text-emerald-900/55 dark:text-white/55">إشعارات غير مقروءة</p><p class="mt-2 text-2xl font-semibold text-emerald-950 dark:text-white">{{ $unreadNotificationsCount }}</p></a>
    </section>

    @if ($latestActiveOrder)
        <section class="relative overflow-hidden rounded-2xl bg-emerald-900 p-6 text-white sm:p-8" aria-labelledby="current-order-title"><div class="absolute inset-y-0 start-0 w-1 bg-amber-400"></div><div class="grid gap-6 sm:grid-cols-[1fr_auto] sm:items-end"><div><p class="text-xs font-semibold text-emerald-200">طلبك الحالي</p><div class="mt-3 flex flex-wrap items-center gap-3"><h2 id="current-order-title" class="text-xl font-semibold"><bdi>{{ $latestActiveOrder->reference }}</bdi></h2><span class="rounded-full bg-white/10 px-3 py-1 text-xs">{{ $latestActiveOrder->status->label() }}</span></div><p class="mt-3 text-sm text-emerald-100">الإجمالي: <x-money :amount-baisa="$latestActiveOrder->total_baisa" :currency="$latestActiveOrder->currency" /></p></div><a href="{{ route('minor.orders.show', $latestActiveOrder->payment_token) }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-sm bg-white px-4 text-sm font-semibold text-emerald-900 transition hover:bg-emerald-50 active:translate-y-px">متابعة الطلب<x-hugeicon name="arrow-left-02" class="text-lg" /></a></div></section>
    @endif

    <div class="grid gap-6 {{ $wallet ? 'lg:grid-cols-[1.2fr_.8fr]' : '' }}">
        @if ($wallet)
        <section id="wallet" class="rounded-2xl border border-emerald-900/10 bg-white p-6 dark:border-white/10 dark:bg-zinc-900" aria-labelledby="wallet-title">
            <div class="flex items-center justify-between gap-3"><h2 id="wallet-title" class="text-lg font-semibold">محفظتي</h2><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs text-emerald-900 dark:bg-white/10 dark:text-white">{{ __('admin_wallets.wallet_statuses.'.$wallet->status) }}</span></div>
            <p class="mt-6 text-sm text-emerald-900/55 dark:text-white/55">الرصيد غير المحجوز</p><p class="mt-2 text-4xl font-semibold text-emerald-950 dark:text-white"><x-money :amount-baisa="max(0, $wallet->balance_baisa - $reservedBalance)" :currency="$wallet->currency" /></p>
            @if ($reservedBalance > 0)<p class="mt-2 text-xs text-amber-700 dark:text-amber-300">محجوز للاسترداد: <x-money :amount-baisa="$reservedBalance" :currency="$wallet->currency" /></p>@endif
            <p class="mt-4 text-sm leading-7 text-emerald-900/60 dark:text-white/60">@if ($wallet->status !== 'active')الدفع غير متاح من هذه المحفظة حاليًا. راجع وليّ الأمر.@elseif (! $profile->wallet_spending_enabled)الدفع من المحفظة غير مفعّل. اطلب من وليّ الأمر تفعيله من حسابه.@elseيمكنك اختيار المحفظة عند إتمام الطلب. شحن الرصيد يتم من حساب وليّ الأمر.@endif</p>
            <div class="mt-6 divide-y divide-emerald-900/10 border-t border-emerald-900/10 dark:divide-white/10 dark:border-white/10">@forelse ($wallet->movements as $movement)<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-medium">{{ __('admin_wallets.types.'.$movement->type) }}</p><p class="mt-1 text-xs text-emerald-900/50 dark:text-white/50"><bdi>{{ $movement->created_at?->format('Y-m-d H:i') }}</bdi></p></div><span dir="ltr" class="text-sm font-semibold {{ $movement->credit_baisa > 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-rose-700 dark:text-rose-300' }}">{{ $movement->credit_baisa > 0 ? '+' : '−' }}{{ number_format(($movement->credit_baisa > 0 ? $movement->credit_baisa : $movement->debit_baisa) / 1000, 3) }} {{ $wallet->currency }}</span></div>@empty<p class="py-6 text-sm text-emerald-900/55 dark:text-white/55">لا توجد حركات في المحفظة بعد.</p>@endforelse</div>
            <a href="{{ route('minor.wallet.movements.index') }}" class="mt-4 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-emerald-700 hover:underline dark:text-emerald-300">عرض كل حركات المحفظة<x-hugeicon name="arrow-left-02" class="text-base" /></a>
        </section>
        @endif

        <div class="space-y-6">
            <section class="rounded-2xl border border-emerald-900/10 bg-white p-6 dark:border-white/10 dark:bg-zinc-900"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">آخر الطلبات</h2><a href="{{ route('minor.orders.index') }}" class="text-sm font-semibold text-emerald-700 hover:underline dark:text-emerald-300">عرض الكل ({{ $ordersCount }})</a></div><div class="mt-4 divide-y divide-emerald-900/10 dark:divide-white/10">@forelse ($recentOrders as $order)<a href="{{ route('minor.orders.show', $order->payment_token) }}" class="flex items-center justify-between gap-3 py-3"><div class="min-w-0"><p class="truncate text-sm font-semibold"><bdi>{{ $order->reference }}</bdi></p><p class="mt-1 text-xs text-emerald-900/50 dark:text-white/50">{{ $order->status->label() }}</p></div><x-hugeicon name="arrow-left-02" class="shrink-0 text-lg text-emerald-700 dark:text-emerald-300" /></a>@empty<p class="py-5 text-sm text-emerald-900/55 dark:text-white/55">لا توجد طلبات بعد.</p>@endforelse</div></section>
            @if ($notifications->isNotEmpty())<section class="rounded-2xl border border-emerald-900/10 bg-white p-6 dark:border-white/10 dark:bg-zinc-900"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">آخر الإشعارات</h2><a href="{{ route('minor.notifications.index') }}" class="text-sm font-semibold text-emerald-700 hover:underline dark:text-emerald-300">عرض الكل</a></div><div class="mt-4 divide-y divide-emerald-900/10 dark:divide-white/10">@foreach ($notifications as $notification)<p class="py-3 text-sm leading-6 text-emerald-900/70 dark:text-white/70">{{ data_get($notification->data, 'message', 'لديك تحديث جديد.') }}</p>@endforeach</div></section>@endif
        </div>
    </div>

    @if ($browserNotifications['enabled'])
        <section @if ($browserNotifications['has_guardian_consent'] && filled($browserNotifications['vapid_public_key'])) data-minor-push-manager data-vapid-public-key="{{ $browserNotifications['vapid_public_key'] }}" data-subscribe-url="{{ $browserNotifications['store_url'] }}" data-unsubscribe-url="{{ $browserNotifications['destroy_url'] }}" @endif class="border-y border-emerald-900/10 py-6 dark:border-white/10" aria-labelledby="browser-notifications-title"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div class="max-w-2xl"><h2 id="browser-notifications-title" class="font-semibold">إشعارات هذا الجهاز</h2>@if (! $browserNotifications['has_guardian_consent'])<p class="mt-2 text-sm text-amber-800 dark:text-amber-200">لم تُسجّل موافقة وليّ الأمر لهذا الحساب.</p>@elseif (blank($browserNotifications['vapid_public_key']))<p class="mt-2 text-sm text-amber-800 dark:text-amber-200">إشعارات المتصفح غير مجهزة في هذه البيئة بعد.</p>@else<p class="mt-2 text-sm leading-7 text-emerald-900/65 dark:text-white/65">فعّل إشعارات الطلبات والمحفظة على هذا الجهاز.</p><p data-push-status role="status" class="mt-1 text-xs text-emerald-800 dark:text-emerald-200">جاري التحقق من دعم الجهاز…</p><p data-push-ios-help class="mt-2 hidden text-xs text-amber-800 dark:text-amber-200">على iPhone وiPad، أضف بيرحاء إلى الشاشة الرئيسية أولًا.</p>@endif</div>@if ($browserNotifications['has_guardian_consent'] && filled($browserNotifications['vapid_public_key']))<div class="flex gap-2"><button type="button" data-push-enable class="min-h-11 rounded-sm bg-emerald-800 px-4 text-sm font-semibold text-white dark:bg-emerald-300 dark:text-emerald-950">تفعيل على هذا الجهاز</button><button type="button" data-push-disable class="hidden min-h-11 rounded-sm border border-emerald-900/15 px-4 text-sm font-semibold">تعطيل هذا الجهاز</button></div>@endif</div></section>
    @endif
</section>
@endsection
