@extends('layouts.public', ['title' => 'طلباتي'])

@section('content')
<section class="flex flex-col gap-6" dir="rtl">
    <div class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 class="text-2xl font-semibold text-emerald-950 dark:text-white">طلباتي</h1><p class="mt-2 text-sm text-emerald-900/70 dark:text-white/70">تابع حالة طلباتك من قهوة بيرحاء.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('coffee') }}" class="rounded-lg border border-emerald-900/20 px-4 py-2 text-sm dark:border-white/10">تصفح القهوة</a><form method="POST" action="{{ route('minor.logout') }}">@csrf<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm text-rose-700 dark:text-rose-200">تسجيل الخروج</button></form></div></div>
    <div class="grid gap-3">@forelse ($orders as $order)<a href="{{ route('minor.orders.show', $order->payment_token) }}" class="rounded-2xl border border-emerald-900/10 bg-white p-5 shadow-sm transition hover:border-emerald-500/40 dark:border-white/10 dark:bg-white/5"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold">{{ $order->reference }}</p><p class="mt-1 text-sm text-emerald-900/60 dark:text-white/60" dir="ltr">{{ $order->created_at->format('Y-m-d H:i') }}</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs text-emerald-800 dark:bg-emerald-300/10 dark:text-emerald-100">{{ $order->status->label() }}</span></div><div class="mt-4 text-sm font-semibold"><x-money :amount-baisa="$order->total_baisa" :currency="$order->currency" /></div></a>@empty<div class="rounded-2xl border border-dashed border-emerald-900/20 p-10 text-center text-sm dark:border-white/10">لا توجد طلبات مرتبطة بحسابك بعد.</div>@endforelse</div>
    @if ($notifications->isNotEmpty())<div class="rounded-2xl border border-emerald-900/10 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5"><h2 class="font-semibold">آخر التنبيهات</h2><div class="mt-3 grid gap-2">@foreach ($notifications as $notification)<a href="{{ data_get($notification->data, 'url', route('minor.orders.index')) }}" class="rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-900 dark:bg-emerald-300/10 dark:text-emerald-100">{{ data_get($notification->data, 'reference') }} — {{ data_get($notification->data, 'status_label') }}</a>@endforeach</div></div>@endif
</section>
@endsection
