@extends('layouts.public', ['title' => 'تفاصيل الطلب'])

@section('content')
<section class="flex flex-col gap-6" dir="rtl">
    <div class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 class="text-2xl font-semibold text-emerald-950 dark:text-white">{{ $order->reference }}</h1><p class="mt-2 text-sm text-emerald-900/70 dark:text-white/70">{{ $order->status->label() }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('minor.orders.index') }}" class="rounded-lg border border-emerald-900/20 px-4 py-2 text-sm dark:border-white/10">طلباتي</a><form method="POST" action="{{ route('minor.logout') }}">@csrf<button class="rounded-lg border border-rose-300 px-4 py-2 text-sm text-rose-700 dark:text-rose-200">تسجيل الخروج</button></form></div></div>
    @if ($errors->any())<div class="rounded-xl border border-rose-300/50 bg-rose-50 px-4 py-3 text-sm text-rose-900 dark:bg-rose-300/10 dark:text-rose-100">{{ $errors->first() }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-[1fr_auto]"><div class="rounded-2xl border border-emerald-900/10 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5"><h2 class="font-semibold">الأصناف</h2><div class="mt-4 grid gap-3">@foreach ($order->items as $item)<div class="flex items-center justify-between gap-4 border-b border-emerald-900/10 pb-3 last:border-0 dark:border-white/10"><div><p class="font-medium">{{ $item->product_name }} · {{ $item->option_name }}</p><p class="text-sm text-emerald-900/60 dark:text-white/60">الكمية: {{ $item->quantity }}</p></div><x-money :amount-baisa="$item->line_total_baisa" :currency="$item->currency" /></div>@endforeach</div><p class="mt-4 border-t border-emerald-900/10 pt-4 text-lg font-bold dark:border-white/10"><x-money :amount-baisa="$order->total_baisa" :currency="$order->currency" /></p></div><aside class="h-fit rounded-2xl border border-emerald-900/10 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/5">@if ($order->status->getValue() === 'pending_payment')<p class="text-sm text-emerald-900/70 dark:text-white/70">إذا كان الدفع المباشر مفعّلًا لحسابك يمكنك المتابعة، وإلا سيصلك وليّ الأمر برابط الدفع.</p><form method="POST" action="{{ route('minor.orders.payment', $order->payment_token) }}" class="mt-4">@csrf<button class="w-full rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">الدفع الآن</button></form>@else<p class="text-sm text-emerald-900/70 dark:text-white/70">ستظهر تحديثات الحالة هنا عند توفرها.</p>@endif</aside></div>
</section>
@endsection
