<div @if ($isPending) wire:poll.10s="refreshStatus" @endif class="mx-auto w-full max-w-4xl">
    <div class="flex flex-col gap-4 border-b border-[#2a8069]/14 pb-6 sm:flex-row sm:items-end sm:justify-between dark:border-white/10">
        <div><p class="text-sm font-bold tracking-[0.18em] text-[#b07c00]">طلب قهوة بيرحاء</p><h1 class="mt-2 font-heading text-3xl font-bold text-[#123329] sm:text-4xl dark:text-[#f7f1df]">{{ $statusLabel }}</h1><p class="mt-2 text-sm text-[#315e52] dark:text-[#d2e7df]/70">رقم الطلب: <span dir="ltr" class="font-bold">{{ $order->reference }}</span></p></div>
        @if ($isPending)<span class="inline-flex items-center gap-2 rounded-full bg-[#fff8e7] px-3 py-2 text-xs font-bold text-[#92400e] dark:bg-[#2d2410] dark:text-[#f9d98b]"><span class="size-2 animate-pulse rounded-full bg-[#b07c00]"></span>بانتظار إتمام الدفع</span>@endif
    </div>
    <div class="mt-8 grid gap-6 lg:grid-cols-[1fr_0.75fr]">
        <section class="rounded-sm border border-[#2a8069]/14 bg-white p-5 dark:border-white/10 dark:bg-white/5"><h2 class="font-heading text-xl font-bold text-[#123329] dark:text-[#f7f1df]">تفاصيل الطلب</h2><div class="mt-5 grid gap-4">@foreach ($order->items as $item)<div class="flex items-start justify-between gap-4 border-b border-[#2a8069]/10 pb-4 last:border-0 last:pb-0 dark:border-white/8"><div><p class="font-bold text-[#123329] dark:text-[#f7f1df]">{{ $item->product_name }}</p><p class="text-sm text-[#315e52] dark:text-[#d2e7df]/65">{{ $item->option_name }} × {{ $item->quantity }}</p></div><p class="font-bold text-[#007a52] dark:text-[#6ee7b7]"><x-money :amount-baisa="$item->line_total_baisa" :currency="$item->currency" /></p></div>@endforeach</div><dl class="mt-6 grid gap-2 border-t border-[#2a8069]/12 pt-4 text-sm dark:border-white/10"><div class="flex justify-between"><dt>المجموع قبل الضريبة</dt><dd><x-money :amount-baisa="$order->subtotal_baisa" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>ضريبة القيمة المضافة (مضمنة)</dt><dd><x-money :amount-baisa="$order->vat_baisa" :currency="$order->currency" /></dd></div><div class="flex justify-between border-t border-[#2a8069]/12 pt-3 text-base font-bold dark:border-white/10"><dt>الإجمالي</dt><dd class="text-[#007a52] dark:text-[#6ee7b7]"><x-money :amount-baisa="$order->total_baisa" :currency="$order->currency" /></dd></div></dl><div class="mt-6 border-t border-[#2a8069]/12 pt-4 text-sm leading-7 dark:border-white/10"><p class="font-bold text-[#123329] dark:text-[#f7f1df]">بيانات الاستلام</p><p class="mt-1 text-[#315e52] dark:text-[#d2e7df]/70">{{ $order->pickup_type === 'scheduled' && $order->pickup_at ? 'موعد محدد: '.$order->pickup_at->format('Y-m-d H:i') : 'الاستلام في أقرب وقت' }}</p></div></section>
        <aside class="h-fit rounded-sm border border-[#2a8069]/14 bg-white p-5 dark:border-white/10 dark:bg-white/5"><h2 class="font-heading text-xl font-bold text-[#123329] dark:text-[#f7f1df]">الخطوة التالية</h2><p class="mt-3 text-sm leading-7 text-[#315e52] dark:text-[#d2e7df]/70">{{ $isPending ? 'أكمل الدفع الآن لتثبيت طلبك. يحتفظ النظام بالمخزون لفترة محدودة.' : 'سنحدّثك بحالة الطلب هنا. يمكنك التواصل معنا إذا احتجت مساعدة.' }}</p>@if ($isPending)<form method="POST" action="{{ URL::temporarySignedRoute('store.orders.payment.store', now()->addHours(12), ['order' => $order->payment_token]) }}" class="mt-5">@csrf<button type="submit" class="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-sm bg-[#007a52] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#006746]">إعادة محاولة الدفع <x-hugeicon name="arrow-left-02" class="text-lg" /></button></form>@endif<a href="{{ route('coffee') }}#menu" class="mt-3 inline-flex min-h-11 w-full items-center justify-center rounded-sm border border-[#2a8069]/18 px-4 py-2 text-sm font-bold text-[#007a52] dark:border-white/12 dark:text-[#6ee7b7]">العودة إلى القائمة</a></aside>
    </div>
</div>
